# Generated by Django 4.0.5 on 2022-07-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='featureimage',
            field=models.ImageField(default=1, upload_to='featureimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnailimage',
            field=models.ImageField(default=2, upload_to='thumbnail'),
            preserve_default=False,
        ),
    ]
